apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: example-app-1
  namespace: example-app-1
spec:
  interval: 1m0s
  path: ./deployment
  prune: true
  sourceRef:
    kind: GitRepository
    name: example-app-1
resources:
  - gitrepository.yaml
  - namespace.yaml