apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: example-app-1
  namespace: example-app-1
spec:
  interval: 1m
  url: https://github.com/Solomon-Apps/example-app-1
  ref:
    branch: main
  secretRef:
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example-app-1
  namespace: example-app-1
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: example-app-1
  prune: true